plugins:
  relative_links:
    enabled: true
    collections: true
    include:
      - CONTRIBUTING.md
      - README.md
      - LICENSE.md
      - COPYING.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - ISSUE_TEMPLATE.md
      - PULL_REQUEST_TEMPLATE.md
    mathjax: true
title: General Stuff
description: Cognitive Load
